CREATE TABLE PLAYER(
	Name		VARCHAR(20)		NOT NULL,
	Position	VARCHAR(20)		NOT NULL,
	Skill_level	INTEGER,
	Salary		INTEGER,
	Team_id		INTEGER,
	Id		INTEGER,
	City		VARCHAR(20),
	PRIMARY KEY (Id),
	FOREIGN KEY (Team_id)	REFERENCES TEAM (Id)
	);

CREATE TABLE TEAM(
	Name		VARCHAR(20)		NOT NULL,
	City		VARCHAR(20)		NOT NULL,
	Coach		VARCHAR(20),
	Id		INTEGER,
	Captain		VARCHAR(20),
	PRIMARY KEY (Name)
	);

CREATE TABLE GAME(
	Id		INTEGER			NOT NULL,
	Host_team	INTEGER			NOT NULL,
	Guest_team	INTEGER			NOT NULL,
	H_T_Score	INTEGER			NOT NULL,
	G_T_Score	INTEGER			NOT NULL,
	Game_date	DATE,
	PRIMARY KEY (Id),
	FOREIGN KEY (Host_team) REFERENCES TEAM(Id),
	FOREIGN KEY (Guest_team) REFERENCES TEAM(Id),
	CHECK (Host_team <> Guest_team)
	);

CREATE TABLE INJURY_RECORDS(
	Id		INTEGER			NOT NULL,
	Inci_desc	VARCHAR(20)		NOT NULL,
	Inj_desc	VARCHAR(20),
	Player_id	INTEGER			NOT NULL,
	FOREIGN KEY (Player_id)		REFERENCES PLAYER(Id)
		ON DELETE SET DEFAULT	ON UPDATE CASCADE
	);
